import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from "next/head";
import { GoogleOAuthProvider } from '@react-oauth/google';
import NavDataComponent from "./components/NavDataComponent";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID}>
      
    <html lang="en">
      <Head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      <body className={inter.className}><NavDataComponent></NavDataComponent>{children}<Footer></Footer></body>
    </html>
    </GoogleOAuthProvider>
  );
}
